# Version 1.0

unstable_features = true
tab_spaces = 2
merge_imports = true
condense_wildcard_suffixes = true
force_multiline_blocks = true
format_macro_matchers = true
match_block_trailing_comma = true
normalize_comments = true
reorder_impl_items = true
struct_lit_single_line = false
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
